(function(root){
'use strict';
const D=(root.SITE_CONTENT||(typeof require!=='undefined'?require('./content.js'):{})).page.sections.verification.content.damage;
const n=v=>v.toLocaleString('ja-JP',{maximumSignificantDigits:7});
const exact=n;
const eq=v=>`${Math.abs(v-Number(v.toPrecision(7)))>Math.max(1,Math.abs(v))*1e-14?'≈':'＝'} ${n(v)}`;
function damageTrace(s,r){
 const {basis,reactionProbability:p,reactionMastery:mastery,reactionUnreacted:unreacted,reactionReacted:reacted}=r;
 const calc=(text,className='')=>`<div class="damage-equation text-secondary${className?' '+className:''}">${text}</div>`;
 const factorValue=(value,suffix='')=>`<span class="factor-value-number">${value}</span><span class="factor-value-trailer"${suffix?'':' aria-hidden="true"'}>${suffix||'&nbsp;'}</span>`;
 const factor=(id,title,value,brief,detail,detailClass='')=>`<details class="damage-factor${brief?'':' no-brief'}" id="damage-${id}"><summary><span class="factor-disclosure disclosure-triangle text-standard" aria-hidden="true"></span><span class="factor-name text-standard">${title}</span>${brief?`<span class="factor-brief text-secondary">${brief}</span>`:''}<strong class="factor-value text-primary-label">${factorValue('×'+n(value))}</strong></summary><div class="factor-detail${detailClass?' '+detailClass:''}">${detail}</div></details>`;
 const simpleFactor=(id,title,value,brief)=>`<div class="damage-factor damage-factor-simple${brief?'':' no-brief'}" id="damage-${id}"><span class="factor-indent" aria-hidden="true"></span><span class="factor-name text-standard">${title}</span>${brief?`<span class="factor-brief text-secondary">${brief}</span>`:''}<strong class="factor-value text-primary-label">${factorValue('×'+n(value))}</strong></div>`;
 const basisTerm=(title,value,suffix='')=>`<div class="damage-factor damage-factor-simple damage-basis-term no-brief"><span class="factor-indent" aria-hidden="true"></span><span class="factor-name text-standard">${title}</span><strong class="factor-value text-primary-label">${factorValue(value,suffix)}</strong></div>`;
 const talentFormula=r.rotation.map(entry=>`${n(entry.rate)} × ${n(entry.count)}`).join(' ＋ ');
 const talentTable=`<div class="talent-table-wrap trace-table-spaced table-standard"><table aria-label="${D.talent}"><thead><tr class="table-standard-header"><th scope="col">${D.talentTable.attackType}</th>${r.rotation.map((entry,index)=>`<th scope="col">${index===0?D.talentTable.normal:entry.name}</th>`).join('')}</tr></thead><tbody><tr><th scope="row" class="text-secondary">${D.talentTable.rate}</th>${r.rotation.map(entry=>`<td class="text-secondary">${n(entry.rate)}</td>`).join('')}</tr><tr><th scope="row" class="text-secondary">${D.talentTable.count}</th>${r.rotation.map(entry=>`<td class="text-secondary">${n(entry.count)}</td>`).join('')}</tr></tbody></table></div>`;
 const basisFactors=basisTerm(D.finalAttack,`（${n(r.atk)}`)+factor('talent',D.talent,r.T,'',`${talentTable}${calc(`${D.talent}<br>＝ ${talentFormula} ${eq(r.T)}`,'card-result')}`,'detail-plain')+basisTerm(D.flat,`＋ ${n(r.totalFlat)}`,'）');
 const resistIndex=r.resValue<0?0:r.resValue<.75?1:2,resistCases=D.resistanceCases,resistSub=[`1 − (${exact(r.resValue)}) ÷ 2`,`1 − ${exact(r.resValue)}`,`1 ÷ (1 ＋ 4 × ${exact(r.resValue)})`][resistIndex];
 const resistTable=`<div class="resistance-rules trace-table-spaced table-standard"><table aria-label="${D.resistance}"><thead><tr class="table-standard-header"><th scope="col">${D.resistanceCondition}</th><th scope="col">${D.resistanceExpression}</th></tr></thead><tbody>${resistCases.map((item,index)=>`<tr class="${index===resistIndex?'applied':''}"><th scope="row" class="${index===resistIndex?'text-secondary-label':'text-secondary'}">${item.condition}${index===resistIndex?`（${D.current}）`:''}</th><td class="${index===resistIndex?'text-secondary-label':'text-secondary'}">${item.formula}</td></tr>`).join('')}</tbody></table></div>`;
 const defenseDebuffTerm=s.def<0?`(1 − ${exact(-s.def/100)})`:`(1 ＋ ${exact(s.def/100)})`;
 const factors=[
 simpleFactor('buff',D.buff,r.buff,''),
 factor('crit',D.crit,r.crit,'',`<div class="crit-table-wrap memory-style-table trace-table-spaced table-standard"><table class="crit-table"><thead><tr class="table-standard-header"><th></th><th>${D.criticalAttack}</th><th>${D.normalAttack}</th></tr></thead><tbody><tr><th class="text-secondary">${D.probability}</th><td>${n(r.critRate)}%</td><td>${n(100-r.critRate)}%</td></tr><tr><th class="text-secondary">${D.critFactor}</th><td>${n(1+r.critDamage/100)}</td><td>1</td></tr></tbody></table></div>${calc(`${D.crit}<br>＝ ${exact(r.critRate/100)} × ${exact(1+r.critDamage/100)} ＋ ${exact(1-r.critRate/100)} × 1<br>＝ ${n(r.crit)}`,'card-result')}`,'detail-plain'),
 factor('reaction',D.reaction,r.reaction,'',`${calc(`${D.reactionCorrection}<br>＝ 見かけの元素反応倍率 × ［1 ＋ ${D.reactionBonus} ＋ 2.78 × ${D.mastery} ÷ (${D.mastery} ＋ 1,400)］<br>＝ ${exact(s.amp)} × ［1 ＋ ${n(15+s.reactionBonus)}% ＋ 2.78 × ${n(r.em)} ÷ (${n(r.em)} ＋ 1,400)］<br>＝ ${exact(s.amp)} × ${n(mastery)} ${eq(s.amp*mastery)}`,'card-result')}<div class="reaction-table-wrap memory-style-table table-standard"><table class="reaction-table"><thead><tr class="table-standard-header"><th></th><th>${D.reacted}</th><th>${D.unreacted}</th></tr></thead><tbody><tr><th class="text-secondary">${D.probability}</th><td>${exact(p)}</td><td>${exact(unreacted)}</td></tr><tr><th class="text-secondary">${D.reactionFactor.replace('の乗算','の<span class="reaction-factor-break"></span>乗算')}</th><td>${n(s.amp*mastery)}</td><td>1</td></tr></tbody></table></div>${calc(`${D.reaction}<br>＝ ${exact(p)} × ${n(s.amp*mastery)} ＋ ${exact(unreacted)} × 1<br>＝ ${n(r.reaction)}`,'card-result')}`,'detail-plain'),
 factor('defense',D.defense,r.def,'',`${calc(`${D.defenseCorrection}<br>＝ ${D.defenseFormula}<br>＝ (${s.level} ＋ 100) ÷ ［(${s.level} ＋ 100) ＋ (${s.enemy} ＋ 100) × ${defenseDebuffTerm} × (1 − ${exact(r.ignore/100)})］<br>${eq(r.def)}`)}<p class="trace-note trace-defense-note text-meta">${D.defenseNote}</p>`,'card-result'),
 factor('resistance',D.resistance,r.res,'',`${resistTable}${calc(`${D.currentCalculation}<br>＝ ${resistSub} ${eq(r.res)}<p class="trace-note text-meta">${D.resistanceNote}</p>`,'card-result')}`,'detail-plain')
 ];
 return `<section class="damage-trace" aria-labelledby="damage-trace-title"><div class="damage-title"><h3 id="damage-trace-title">${D.title}</h3></div>
 <section class="damage-stage" id="damage-factors">${D.caption?`<p class="damage-caption text-meta">${D.caption}</p>`:''}<div class="damage-factor-list">${basisFactors}${factors.join('')}</div></section>
 <section class="damage-answer" aria-label="${D.answerAria}"><span class="text-standard">${D.answerFormula}</span><p class="text-secondary">≈（${n(r.atk)} × ${n(r.T)} ＋ ${n(r.totalFlat)}）× ${[r.buff,r.crit,r.reaction,r.def,r.res].map(n).join(' × ')}</p><strong class="text-medium-result">≈ ${Math.round(r.total).toLocaleString('ja-JP')}</strong><small class="text-meta">${D.answerNote}</small></section>
 ${D.roundingNote?`<p class="damage-caption text-meta">${D.roundingNote}</p>`:''}</section>`;
}
root.damageTrace=damageTrace;
if(typeof module!=='undefined')module.exports=damageTrace;
})(globalThis);
